In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [18]:
df_01 = pd.read_excel("../data/ref_data/CIV1159_W2026_FP_Task2data.xlsx", sheet_name="Structure 1")
df_02 = pd.read_excel("../data/ref_data/CIV1159_W2026_FP_Task2data.xlsx", sheet_name="Structure 2")
df_03 = pd.read_excel("../data/ref_data/CIV1159_W2026_FP_Task2data.xlsx", sheet_name="Structure 3")

In [23]:
# Assume the column is 'Date (ddmm)' and values are like '2506' (25th June)
date_str = df_01['Date (ddmm)'].astype(str).str.zfill(4)  # Pad with zeros if needed
day = date_str.str[:-2]  # All but last 2 chars
month = date_str.str[-2:]  # Last 2 chars

# Ensure all values are strings and 4 digits (e.g., '0106' for June 1)
df_01['Date (ddmm)'] = df_01['Date (ddmm)'].astype(str).str.zfill(4)
df_01['Date (ddmm)']

0      1900-01-01
1      1900-01-02
2      1900-01-03
3      1900-01-04
4      1900-01-05
          ...
360    1900-12-27
361    1900-12-28
362    1900-12-29
363    1900-12-30
364    1900-12-31
Name: Date (ddmm), Length: 365, dtype: object

In [22]:
df_01['Date (ddmm)'] = pd.to_datetime(df_01['Date (ddmm)'].astype(str), format='%d%m')
df_01.head()

  Date (ddmm)  Strain (με)
0  1900-01-01        292.8
1  1900-01-02        298.1
2  1900-01-03        295.5
3  1900-01-04        305.5
4  1900-01-05        297.7

In [ ]:
df_02.head()

   Date (ddmm)  Strain (με)
0          101         97.4
1          201        104.2
2          301        104.4
3          401         98.9
4          501        106.1

In [ ]:
df_03.head()

   Date (ddmm)  Strain (με)
0          101         87.4
1          201         82.4
2          301         86.4
3          401         82.3
4          501         93.9